### ISSUE TITLE
Break up Xer.Cqrs projects to own repositories

### ISSUE THREAD

**Issue by jeyjeyemem** [XerProjects/Xer.Cqrs#8]
Should we move Xer.Cqrs.CommancdStack, Xer.Cqrs.Event.Stack, and Xer.Cqrs.QueryStack to their own repositories?

**Comment by jeyjeyemem** [comment]
@mvput What do you think about this?

**Comment by mvput** [comment]
Hm difficult. I won't split up to much at the beginning i think. Maybe for the future?

**Comment by jeyjeyemem** [comment]
Sure. I'm closing this out.
